//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursovou.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barber
    {
        public int IDBarber { get; set; }
        public string NameBarber { get; set; }
        public string DoljnostBarbera { get; set; }
        public string AdressBarbershopa { get; set; }
    
        public virtual Zapisi Zapisi { get; set; }
    }
}
