//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursovou.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market
    {
        public Market()
        {
            this.Zapisi = new HashSet<Zapisi>();
        }
    
        public int IDMarket { get; set; }
        public string NazvanieTovara { get; set; }
        public string OpisanieTovara { get; set; }
        public string StoimostTovara { get; set; }
    
        public virtual ServisePage ServisePage { get; set; }
        public virtual ICollection<Zapisi> Zapisi { get; set; }
    }
}
