//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursovou.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BarberShopEntities1 : DbContext
    {
        public static BarberShopEntities1 _context;

        public static BarberShopEntities1 GetContext()
        {
            if (_context == null)
                _context = new BarberShopEntities1();
            return _context;
        }
        

        public BarberShopEntities1()
            : base("name=BarberShopEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Barber> Barber { get; set; }
        public DbSet<Klient> Klient { get; set; }
        public DbSet<Market> Market { get; set; }
        public DbSet<ServisePage> ServisePage { get; set; }
        public DbSet<Zapisi> Zapisi { get; set; }
    }
}
