//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursovou.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapisi
    {
        public int IDZapisi { get; set; }
        public int NazvanieYslygi { get; set; }
        public int StoimostYslygi { get; set; }
        public System.DateTime DataZapisi { get; set; }
        public Nullable<int> IDMarket { get; set; }
    
        public virtual Barber Barber { get; set; }
        public virtual Market Market { get; set; }
    }
}
